### ISSUE TITLE
Set concurrency group for all jobs that target a deployment environment

### ISSUE THREAD

**Issue by hknutsen** [equinor/ops-actions#252]
For all jobs that target a deployment environment (i.e. a value is provided for `environment`), add the job to a common concurrency group (e.g. `deployment @ <environment>`) to ensure only a single deployment is created for a given environment at all times.

## Tasks

- [ ] Set concurrency group for `azure-function.yml`
- [ ] Set concurrency group for `azure-webapp.yml`
- [x] Set concurrency group for `github-pages.yml`
- [x] Set concurrency group for `terraform.yml`
